import { Location } from "./types";

export const locations: Location[] = [
  { location_id: "ba_la_plata", location_name: "La Plata", province_name: "Buenos Aires", latitude: -34.9214, longitude: -57.9544, country_code: "AR", is_active: true },
  { location_id: "ba_bahia_blanca", location_name: "Bahía Blanca", province_name: "Buenos Aires", latitude: -38.7183, longitude: -62.2663, country_code: "AR", is_active: true },
  { location_id: "ba_pergamino", location_name: "Pergamino", province_name: "Buenos Aires", latitude: -33.8949, longitude: -60.5736, country_code: "AR", is_active: true },
  { location_id: "ba_junin", location_name: "Junín", province_name: "Buenos Aires", latitude: -34.5939, longitude: -60.9469, country_code: "AR", is_active: true },
  { location_id: "ba_azul", location_name: "Azul", province_name: "Buenos Aires", latitude: -36.7776, longitude: -59.8586, country_code: "AR", is_active: true },
  { location_id: "ba_tandil", location_name: "Tandil", province_name: "Buenos Aires", latitude: -37.3217, longitude: -59.1332, country_code: "AR", is_active: true },
  { location_id: "ba_olavarria", location_name: "Olavarría", province_name: "Buenos Aires", latitude: -36.8927, longitude: -60.3225, country_code: "AR", is_active: true },
  { location_id: "ba_pehuajo", location_name: "Pehuajó", province_name: "Buenos Aires", latitude: -35.8108, longitude: -61.8969, country_code: "AR", is_active: true },
  { location_id: "ba_tres_arroyos", location_name: "Tres Arroyos", province_name: "Buenos Aires", latitude: -38.3733, longitude: -60.2758, country_code: "AR", is_active: true },
  { location_id: "ba_balcarce", location_name: "Balcarce", province_name: "Buenos Aires", latitude: -37.8453, longitude: -57.7311, country_code: "AR", is_active: true },
  { location_id: "ba_nueve_de_julio", location_name: "9 de Julio", province_name: "Buenos Aires", latitude: -35.4421, longitude: -60.8842, country_code: "AR", is_active: true },
  { location_id: "ba_bragado", location_name: "Bragado", province_name: "Buenos Aires", latitude: -35.1167, longitude: -60.5, country_code: "AR", is_active: true },
  { location_id: "ba_chivilcoy", location_name: "Chivilcoy", province_name: "Buenos Aires", latitude: -34.8956, longitude: -60.0167, country_code: "AR", is_active: true },
  { location_id: "ba_lincoln", location_name: "Lincoln", province_name: "Buenos Aires", latitude: -34.8667, longitude: -61.5333, country_code: "AR", is_active: true },
  { location_id: "ba_general_villegas", location_name: "General Villegas", province_name: "Buenos Aires", latitude: -35.0333, longitude: -63.0167, country_code: "AR", is_active: true },
  { location_id: "ba_dolores", location_name: "Dolores", province_name: "Buenos Aires", latitude: -36.3167, longitude: -57.6833, country_code: "AR", is_active: true },
  { location_id: "ba_mar_del_plata", location_name: "Mar del Plata", province_name: "Buenos Aires", latitude: -38.0055, longitude: -57.5426, country_code: "AR", is_active: true },
  { location_id: "cba_cordoba", location_name: "Córdoba", province_name: "Córdoba", latitude: -31.4201, longitude: -64.1888, country_code: "AR", is_active: true },
  { location_id: "cba_rio_cuarto", location_name: "Río Cuarto", province_name: "Córdoba", latitude: -33.1301, longitude: -64.3495, country_code: "AR", is_active: true },
  { location_id: "cba_villa_maria", location_name: "Villa María", province_name: "Córdoba", latitude: -32.4075, longitude: -63.2402, country_code: "AR", is_active: true },
  { location_id: "cba_marcos_juarez", location_name: "Marcos Juárez", province_name: "Córdoba", latitude: -32.6978, longitude: -62.1067, country_code: "AR", is_active: true },
  { location_id: "cba_san_francisco", location_name: "San Francisco", province_name: "Córdoba", latitude: -31.4354, longitude: -62.0713, country_code: "AR", is_active: true },
  { location_id: "cba_rio_tercero", location_name: "Río Tercero", province_name: "Córdoba", latitude: -32.1729, longitude: -64.1141, country_code: "AR", is_active: true },
  { location_id: "cba_villa_carlos_paz", location_name: "Villa Carlos Paz", province_name: "Córdoba", latitude: -31.4241, longitude: -64.4978, country_code: "AR", is_active: true },
  { location_id: "cba_rio_primero", location_name: "Río Primero", province_name: "Córdoba", latitude: -31.3333, longitude: -63.8667, country_code: "AR", is_active: true },
  { location_id: "cba_justiniano_posse", location_name: "Justiniano Posse", province_name: "Córdoba", latitude: -32.8833, longitude: -62.2833, country_code: "AR", is_active: true },
  { location_id: "cba_laboulaye", location_name: "Laboulaye", province_name: "Córdoba", latitude: -34.1333, longitude: -64.4, country_code: "AR", is_active: true },
  { location_id: "cba_vicuna_mackenna", location_name: "Vicuña Mackenna", province_name: "Córdoba", latitude: -33.9, longitude: -64.3833, country_code: "AR", is_active: true },
  { location_id: "sf_rosario", location_name: "Rosario", province_name: "Santa Fe", latitude: -32.9587, longitude: -60.693, country_code: "AR", is_active: true },
  { location_id: "sf_santa_fe", location_name: "Santa Fe", province_name: "Santa Fe", latitude: -31.6333, longitude: -60.7, country_code: "AR", is_active: true },
  { location_id: "sf_venado_tuerto", location_name: "Venado Tuerto", province_name: "Santa Fe", latitude: -33.7456, longitude: -61.9689, country_code: "AR", is_active: true },
  { location_id: "sf_rafaela", location_name: "Rafaela", province_name: "Santa Fe", latitude: -31.2503, longitude: -61.4867, country_code: "AR", is_active: true },
  { location_id: "sf_reconquista", location_name: "Reconquista", province_name: "Santa Fe", latitude: -29.1444, longitude: -59.6439, country_code: "AR", is_active: true },
  { location_id: "sf_esperanza", location_name: "Esperanza", province_name: "Santa Fe", latitude: -31.4489, longitude: -60.9317, country_code: "AR", is_active: true },
  { location_id: "sf_sunchales", location_name: "Sunchales", province_name: "Santa Fe", latitude: -30.9333, longitude: -61.5667, country_code: "AR", is_active: true },
  { location_id: "sf_villa_constitucion", location_name: "Villa Constitución", province_name: "Santa Fe", latitude: -33.2333, longitude: -60.3333, country_code: "AR", is_active: true },
  { location_id: "sf_ceres", location_name: "Ceres", province_name: "Santa Fe", latitude: -29.8833, longitude: -61.95, country_code: "AR", is_active: true },
  { location_id: "sf_el_trebol", location_name: "El Trébol", province_name: "Santa Fe", latitude: -32.2, longitude: -61.7, country_code: "AR", is_active: true },
  { location_id: "er_parana", location_name: "Paraná", province_name: "Entre Ríos", latitude: -31.7333, longitude: -60.5167, country_code: "AR", is_active: true },
  { location_id: "er_concordia", location_name: "Concordia", province_name: "Entre Ríos", latitude: -31.3928, longitude: -58.0209, country_code: "AR", is_active: true },
  { location_id: "er_gualeguaychu", location_name: "Gualeguaychú", province_name: "Entre Ríos", latitude: -33.0078, longitude: -58.5111, country_code: "AR", is_active: true },
  { location_id: "er_gualeguay", location_name: "Gualeguay", province_name: "Entre Ríos", latitude: -33.15, longitude: -59.3167, country_code: "AR", is_active: true },
  { location_id: "er_concepcion_del_uruguay", location_name: "Concepción del Uruguay", province_name: "Entre Ríos", latitude: -32.4833, longitude: -58.2333, country_code: "AR", is_active: true },
  { location_id: "er_victoria", location_name: "Victoria", province_name: "Entre Ríos", latitude: -32.6167, longitude: -60.15, country_code: "AR", is_active: true },
  { location_id: "er_federacion", location_name: "Federación", province_name: "Entre Ríos", latitude: -30.9833, longitude: -58.0167, country_code: "AR", is_active: true },
  { location_id: "er_nogoya", location_name: "Nogoyá", province_name: "Entre Ríos", latitude: -32.3833, longitude: -59.8, country_code: "AR", is_active: true },
  { location_id: "corr_corrientes", location_name: "Corrientes", province_name: "Corrientes", latitude: -27.4806, longitude: -58.8341, country_code: "AR", is_active: true },
  { location_id: "corr_goya", location_name: "Goya", province_name: "Corrientes", latitude: -29.1397, longitude: -59.2656, country_code: "AR", is_active: true },
  { location_id: "corr_paso_libres", location_name: "Paso de los Libres", province_name: "Corrientes", latitude: -29.7125, longitude: -57.0875, country_code: "AR", is_active: true },
  { location_id: "corr_mercedes", location_name: "Mercedes", province_name: "Corrientes", latitude: -29.1833, longitude: -58.0833, country_code: "AR", is_active: true },
  { location_id: "corr_curuzu_cuatia", location_name: "Curuzú Cuatiá", province_name: "Corrientes", latitude: -29.7833, longitude: -58.05, country_code: "AR", is_active: true },
  { location_id: "chaco_resistencia", location_name: "Resistencia", province_name: "Chaco", latitude: -27.4511, longitude: -58.9867, country_code: "AR", is_active: true },
  { location_id: "chaco_saenz_pena", location_name: "Sáenz Peña", province_name: "Chaco", latitude: -26.7833, longitude: -60.45, country_code: "AR", is_active: true },
  { location_id: "chaco_villa_angela", location_name: "Villa Ángela", province_name: "Chaco", latitude: -27.5833, longitude: -60.7167, country_code: "AR", is_active: true },
  { location_id: "chaco_charata", location_name: "Charata", province_name: "Chaco", latitude: -27.2167, longitude: -61.2, country_code: "AR", is_active: true },
  { location_id: "sgo_santiago", location_name: "Santiago del Estero", province_name: "Santiago del Estero", latitude: -27.7833, longitude: -64.2667, country_code: "AR", is_active: true },
  { location_id: "sgo_la_banda", location_name: "La Banda", province_name: "Santiago del Estero", latitude: -27.7333, longitude: -64.25, country_code: "AR", is_active: true },
  { location_id: "sgo_frias", location_name: "Frías", province_name: "Santiago del Estero", latitude: -28.65, longitude: -65.15, country_code: "AR", is_active: true },
  { location_id: "salta_salta", location_name: "Salta", province_name: "Salta", latitude: -24.7821, longitude: -65.4232, country_code: "AR", is_active: true },
  { location_id: "salta_tartagal", location_name: "Tartagal", province_name: "Salta", latitude: -22.5167, longitude: -63.8, country_code: "AR", is_active: true },
  { location_id: "salta_oran", location_name: "Orán", province_name: "Salta", latitude: -23.1333, longitude: -64.3167, country_code: "AR", is_active: true },
  { location_id: "salta_metan", location_name: "Metán", province_name: "Salta", latitude: -25.5, longitude: -64.9667, country_code: "AR", is_active: true },
  { location_id: "tuc_tucuman", location_name: "San Miguel de Tucumán", province_name: "Tucumán", latitude: -26.8083, longitude: -65.2176, country_code: "AR", is_active: true },
  { location_id: "tuc_concepcion", location_name: "Concepción", province_name: "Tucumán", latitude: -27.3456, longitude: -65.5986, country_code: "AR", is_active: true },
  { location_id: "tuc_famailla", location_name: "Famaillá", province_name: "Tucumán", latitude: -27.05, longitude: -65.4, country_code: "AR", is_active: true },
  { location_id: "cat_catamarca", location_name: "San Fernando del Valle de Catamarca", province_name: "Catamarca", latitude: -28.4696, longitude: -65.7795, country_code: "AR", is_active: true },
  { location_id: "cat_andalgala", location_name: "Andalgalá", province_name: "Catamarca", latitude: -27.5833, longitude: -66.3167, country_code: "AR", is_active: true },
  { location_id: "cat_belen", location_name: "Belén", province_name: "Catamarca", latitude: -27.65, longitude: -67.0167, country_code: "AR", is_active: true },
  { location_id: "lr_la_rioja", location_name: "La Rioja", province_name: "La Rioja", latitude: -29.4131, longitude: -66.8558, country_code: "AR", is_active: true },
  { location_id: "lr_chilecito", location_name: "Chilecito", province_name: "La Rioja", latitude: -29.1667, longitude: -67.5, country_code: "AR", is_active: true },
  { location_id: "sj_san_juan", location_name: "San Juan", province_name: "San Juan", latitude: -31.5375, longitude: -68.5364, country_code: "AR", is_active: true },
  { location_id: "sj_rawson", location_name: "Rawson", province_name: "San Juan", latitude: -31.7, longitude: -68.3333, country_code: "AR", is_active: true },
  { location_id: "sj_jachal", location_name: "Jáchal", province_name: "San Juan", latitude: -30.2333, longitude: -68.75, country_code: "AR", is_active: true },
  { location_id: "men_mendoza", location_name: "Mendoza", province_name: "Mendoza", latitude: -32.8895, longitude: -68.8458, country_code: "AR", is_active: true },
  { location_id: "men_san_rafael", location_name: "San Rafael", province_name: "Mendoza", latitude: -34.6177, longitude: -68.3301, country_code: "AR", is_active: true },
  { location_id: "men_general_alvear", location_name: "General Alvear", province_name: "Mendoza", latitude: -34.9833, longitude: -67.7, country_code: "AR", is_active: true },
  { location_id: "men_lujan", location_name: "Luján de Cuyo", province_name: "Mendoza", latitude: -33.0333, longitude: -68.8833, country_code: "AR", is_active: true },
  { location_id: "men_tunuyan", location_name: "Tunuyán", province_name: "Mendoza", latitude: -33.5667, longitude: -69.0167, country_code: "AR", is_active: true },
  { location_id: "sl_san_luis", location_name: "San Luis", province_name: "San Luis", latitude: -33.295, longitude: -66.3356, country_code: "AR", is_active: true },
  { location_id: "sl_villa_mercedes", location_name: "Villa Mercedes", province_name: "San Luis", latitude: -33.6833, longitude: -65.4667, country_code: "AR", is_active: true },
  { location_id: "sl_san_martin", location_name: "San Martín", province_name: "San Luis", latitude: -33.0833, longitude: -66.0833, country_code: "AR", is_active: true },
  { location_id: "pampa_santa_rosa", location_name: "Santa Rosa", province_name: "La Pampa", latitude: -36.6167, longitude: -64.2833, country_code: "AR", is_active: true },
  { location_id: "pampa_general_pico", location_name: "General Pico", province_name: "La Pampa", latitude: -35.6586, longitude: -63.7578, country_code: "AR", is_active: true },
  { location_id: "pampa_toay", location_name: "Toay", province_name: "La Pampa", latitude: -36.6833, longitude: -64.3833, country_code: "AR", is_active: true },
  { location_id: "pampa_25_de_mayo", location_name: "25 de Mayo", province_name: "La Pampa", latitude: -37.8667, longitude: -64.7167, country_code: "AR", is_active: true },
  { location_id: "neu_neuquen", location_name: "Neuquén", province_name: "Neuquén", latitude: -38.9516, longitude: -68.0591, country_code: "AR", is_active: true },
  { location_id: "neu_cutral_co", location_name: "Cutral Có", province_name: "Neuquén", latitude: -38.9333, longitude: -69.2333, country_code: "AR", is_active: true },
  { location_id: "neu_plaza_huincul", location_name: "Plaza Huincul", province_name: "Neuquén", latitude: -38.9333, longitude: -69.2, country_code: "AR", is_active: true },
  { location_id: "rn_viedma", location_name: "Viedma", province_name: "Río Negro", latitude: -40.8135, longitude: -62.9967, country_code: "AR", is_active: true },
  { location_id: "rn_general_roca", location_name: "General Roca", province_name: "Río Negro", latitude: -39.0333, longitude: -67.5833, country_code: "AR", is_active: true },
  { location_id: "rn_choele_choel", location_name: "Choele Choel", province_name: "Río Negro", latitude: -39.2667, longitude: -65.65, country_code: "AR", is_active: true },
  { location_id: "rn_cinco_saltos", location_name: "Cinco Saltos", province_name: "Río Negro", latitude: -38.8167, longitude: -68.0667, country_code: "AR", is_active: true },
  { location_id: "chu_trelew", location_name: "Trelew", province_name: "Chubut", latitude: -43.25, longitude: -65.3, country_code: "AR", is_active: true },
  { location_id: "chu_comodoro", location_name: "Comodoro Rivadavia", province_name: "Chubut", latitude: -45.8646, longitude: -67.4938, country_code: "AR", is_active: true },
  { location_id: "chu_sarmiento", location_name: "Sarmiento", province_name: "Chubut", latitude: -45.6, longitude: -69.0833, country_code: "AR", is_active: true },
  { location_id: "sc_rio_gallegos", location_name: "Río Gallegos", province_name: "Santa Cruz", latitude: -51.6226, longitude: -69.2181, country_code: "AR", is_active: true },
  { location_id: "sc_caleta_olivia", location_name: "Caleta Olivia", province_name: "Santa Cruz", latitude: -46.4397, longitude: -67.5283, country_code: "AR", is_active: true },
  { location_id: "tf_rio_grande", location_name: "Río Grande", province_name: "Tierra del Fuego", latitude: -53.7833, longitude: -67.7, country_code: "AR", is_active: true },
  { location_id: "tf_ushuaia", location_name: "Ushuaia", province_name: "Tierra del Fuego", latitude: -54.8019, longitude: -68.303, country_code: "AR", is_active: true },
  { location_id: "for_formosa", location_name: "Formosa", province_name: "Formosa", latitude: -26.1849, longitude: -58.1731, country_code: "AR", is_active: true },
  { location_id: "for_clorinda", location_name: "Clorinda", province_name: "Formosa", latitude: -25.2833, longitude: -57.7167, country_code: "AR", is_active: true },
  { location_id: "mis_posadas", location_name: "Posadas", province_name: "Misiones", latitude: -27.3621, longitude: -55.9008, country_code: "AR", is_active: true },
  { location_id: "mis_obrera", location_name: "Oberá", province_name: "Misiones", latitude: -27.4833, longitude: -55.1167, country_code: "AR", is_active: true },
  { location_id: "mis_eldorado", location_name: "Eldorado", province_name: "Misiones", latitude: -26.4, longitude: -54.6167, country_code: "AR", is_active: true },
  { location_id: "mis_apostoles", location_name: "Apóstoles", province_name: "Misiones", latitude: -27.9167, longitude: -55.7167, country_code: "AR", is_active: true },
  { location_id: "juj_san_salvador", location_name: "San Salvador de Jujuy", province_name: "Jujuy", latitude: -24.1858, longitude: -65.2995, country_code: "AR", is_active: true },
  { location_id: "juj_libertador", location_name: "Libertador General San Martín", province_name: "Jujuy", latitude: -23.8167, longitude: -64.7833, country_code: "AR", is_active: true },
  { location_id: "juj_perico", location_name: "Perico", province_name: "Jujuy", latitude: -24.3833, longitude: -65.1167, country_code: "AR", is_active: true },
  { location_id: "cba_rio_segundo", location_name: "Río Segundo", province_name: "Córdoba", latitude: -31.65, longitude: -63.9167, country_code: "AR", is_active: true },
  { location_id: "cba_alejandro_roca", location_name: "Alejandro Roca", province_name: "Córdoba", latitude: -33.35, longitude: -63.7167, country_code: "AR", is_active: true },
];

export const provinces = [
  "Buenos Aires",
  "Córdoba", 
  "Santa Fe",
  "Entre Ríos",
  "Corrientes",
  "Chaco",
  "Santiago del Estero",
  "Salta",
  "Tucumán",
  "Catamarca",
  "La Rioja",
  "San Juan",
  "Mendoza",
  "San Luis",
  "La Pampa",
  "Neuquén",
  "Río Negro",
  "Chubut",
  "Santa Cruz",
  "Tierra del Fuego",
  "Formosa",
  "Misiones",
  "Jujuy"
];
