{{ config(
    tags=['agro', 'mart', 'app', 'frontend', 'snapshot'],
    cluster_by=['province_key']
) }}

WITH ranked_weather AS (
    SELECT
        weather.location_id,
        weather.location_name AS weather_location_name,
        weather.province_name AS weather_province_name,
        weather.province_key AS weather_province_key,
        weather.latitude AS weather_latitude,
        weather.longitude AS weather_longitude,
        weather.country_code AS weather_country_code,
        weather.is_active_location,
        weather.date AS snapshot_date,
        weather.campaign_name,
        weather.max_air_temp_c,
        weather.min_air_temp_c,
        weather.avg_air_temp_c,
        weather.dew_point_temp_c,
        weather.wet_bulb_temp_c,
        weather.soil_surface_temp_c,
        weather.precipitation_mm,
        weather.relative_humidity_pct,
        weather.specific_humidity_kg_kg,
        weather.solar_radiation_allsky_mj_m2_day,
        weather.solar_radiation_clearsky_mj_m2_day,
        weather.wind_speed_mps,
        weather.wind_speed_max_mps,
        weather.wind_direction_deg,
        weather.surface_pressure_kpa,
        weather.cloud_cover_pct,
        weather.temp_range_c,
        weather.clear_sky_radiation_gap_mj_m2_day,
        weather.heat_index_c,
        weather.wind_chill_c,
        weather.vpd_kpa,
        weather.gdd_base_10_c_days,
        weather.weather_variable_non_null_count,
        weather.critical_null_count,
        weather.has_high_missing_data,
        weather.temperature_inconsistent,
        weather.temperature_outlier,
        weather.precipitation_outlier,
        weather.wind_outlier,
        weather.radiation_inconsistent,
        weather.frost_day,
        weather.heat_stress_day,
        weather.heavy_rain_day,
        weather.dry_day,
        weather.fungal_risk_day,
        weather.is_partial_latest_day,
        weather.is_quality_approved,
        weather.has_location_dimension,
        weather.source_name,
        weather.source_type,
        weather.source_loaded_at,
        weather.record_loaded_at,
        weather._sdc_received_at,
        weather._sdc_extracted_at,
        weather._sdc_sequence,
        ROW_NUMBER() OVER (
            PARTITION BY weather.location_id
            ORDER BY
                CASE
                    WHEN
                        weather.is_quality_approved
                        AND NOT weather.is_partial_latest_day THEN 0
                    ELSE 1
                END,
                weather.date DESC,
                weather.record_loaded_at DESC,
                weather._sdc_received_at DESC,
                weather._sdc_extracted_at DESC,
                weather._sdc_sequence DESC
        ) AS snapshot_rank
    FROM {{ ref('fct_weather_daily') }} AS weather
),

selected_weather AS (
    SELECT
        ranked_weather.location_id,
        ranked_weather.weather_location_name,
        ranked_weather.weather_province_name,
        ranked_weather.weather_province_key,
        ranked_weather.weather_latitude,
        ranked_weather.weather_longitude,
        ranked_weather.weather_country_code,
        ranked_weather.is_active_location,
        ranked_weather.snapshot_date,
        ranked_weather.campaign_name,
        ranked_weather.max_air_temp_c,
        ranked_weather.min_air_temp_c,
        ranked_weather.avg_air_temp_c,
        ranked_weather.dew_point_temp_c,
        ranked_weather.wet_bulb_temp_c,
        ranked_weather.soil_surface_temp_c,
        ranked_weather.precipitation_mm,
        ranked_weather.relative_humidity_pct,
        ranked_weather.specific_humidity_kg_kg,
        ranked_weather.solar_radiation_allsky_mj_m2_day,
        ranked_weather.solar_radiation_clearsky_mj_m2_day,
        ranked_weather.wind_speed_mps,
        ranked_weather.wind_speed_max_mps,
        ranked_weather.wind_direction_deg,
        ranked_weather.surface_pressure_kpa,
        ranked_weather.cloud_cover_pct,
        ranked_weather.temp_range_c,
        ranked_weather.clear_sky_radiation_gap_mj_m2_day,
        ranked_weather.heat_index_c,
        ranked_weather.wind_chill_c,
        ranked_weather.vpd_kpa,
        ranked_weather.gdd_base_10_c_days,
        ranked_weather.weather_variable_non_null_count,
        ranked_weather.critical_null_count,
        ranked_weather.has_high_missing_data,
        ranked_weather.temperature_inconsistent,
        ranked_weather.temperature_outlier,
        ranked_weather.precipitation_outlier,
        ranked_weather.wind_outlier,
        ranked_weather.radiation_inconsistent,
        ranked_weather.frost_day,
        ranked_weather.heat_stress_day,
        ranked_weather.heavy_rain_day,
        ranked_weather.dry_day,
        ranked_weather.fungal_risk_day,
        ranked_weather.is_partial_latest_day,
        ranked_weather.is_quality_approved,
        ranked_weather.has_location_dimension,
        ranked_weather.source_name,
        ranked_weather.source_type,
        ranked_weather.source_loaded_at,
        ranked_weather.record_loaded_at,
        ranked_weather._sdc_received_at,
        ranked_weather._sdc_extracted_at,
        ranked_weather._sdc_sequence,
        CASE
            WHEN
                ranked_weather.is_quality_approved
                AND NOT ranked_weather.is_partial_latest_day THEN 'usable'
            ELSE 'fallback'
        END AS selection_strategy
    FROM ranked_weather
    WHERE snapshot_rank = 1
),

snapshot_base AS (
    SELECT
        selected_weather.location_id,
        location_dim.department_name,
        location_dim.department_key,
        location_dim.municipality_name,
        location_dim.elevation_m,
        location_dim.source_catalog,
        selected_weather.source_name,
        selected_weather.source_loaded_at,
        selected_weather.record_loaded_at,
        location_dim.is_catalog_location,
        selected_weather.has_location_dimension,
        selected_weather.snapshot_date,
        selected_weather.campaign_name,
        selected_weather.max_air_temp_c,
        selected_weather.min_air_temp_c,
        selected_weather.avg_air_temp_c,
        selected_weather.dew_point_temp_c,
        selected_weather.wet_bulb_temp_c,
        selected_weather.soil_surface_temp_c,
        selected_weather.precipitation_mm,
        selected_weather.relative_humidity_pct,
        selected_weather.specific_humidity_kg_kg,
        selected_weather.solar_radiation_allsky_mj_m2_day,
        selected_weather.solar_radiation_clearsky_mj_m2_day,
        selected_weather.wind_speed_mps,
        selected_weather.wind_speed_max_mps,
        selected_weather.wind_direction_deg,
        selected_weather.surface_pressure_kpa,
        selected_weather.cloud_cover_pct,
        selected_weather.temp_range_c,
        selected_weather.clear_sky_radiation_gap_mj_m2_day,
        selected_weather.heat_index_c,
        selected_weather.wind_chill_c,
        selected_weather.vpd_kpa,
        selected_weather.gdd_base_10_c_days,
        selected_weather.weather_variable_non_null_count,
        selected_weather.critical_null_count,
        selected_weather.has_high_missing_data,
        selected_weather.temperature_inconsistent,
        selected_weather.temperature_outlier,
        selected_weather.precipitation_outlier,
        selected_weather.wind_outlier,
        selected_weather.radiation_inconsistent,
        selected_weather.frost_day,
        selected_weather.heat_stress_day,
        selected_weather.heavy_rain_day,
        selected_weather.dry_day,
        selected_weather.fungal_risk_day,
        selected_weather.is_partial_latest_day,
        selected_weather.is_quality_approved,
        selected_weather.selection_strategy,
        selected_weather._sdc_received_at,
        selected_weather._sdc_extracted_at,
        selected_weather._sdc_sequence,
        COALESCE(location_dim.location_name, selected_weather.weather_location_name) AS location_name,
        COALESCE(location_dim.province_name, selected_weather.weather_province_name) AS province_name,
        COALESCE(location_dim.province_key, selected_weather.weather_province_key) AS province_key,
        COALESCE(location_dim.latitude, selected_weather.weather_latitude) AS latitude,
        COALESCE(location_dim.longitude, selected_weather.weather_longitude) AS longitude,
        COALESCE(location_dim.country_code, selected_weather.weather_country_code, 'AR') AS country_code,
        COALESCE(location_dim.is_active, selected_weather.is_active_location, TRUE) AS is_active,
        COALESCE(selected_weather.source_type, location_dim.source_type) AS source_type
    FROM selected_weather
    LEFT JOIN {{ ref('dim_location') }} AS location_dim
        ON selected_weather.location_id = location_dim.location_id
),

scored_snapshot AS (
    SELECT
        snapshot_base.location_id,
        snapshot_base.location_name,
        snapshot_base.province_name,
        snapshot_base.province_key,
        snapshot_base.latitude,
        snapshot_base.longitude,
        snapshot_base.country_code,
        snapshot_base.is_active,
        snapshot_base.department_name,
        snapshot_base.department_key,
        snapshot_base.municipality_name,
        snapshot_base.elevation_m,
        snapshot_base.source_catalog,
        snapshot_base.source_type,
        snapshot_base.source_name,
        snapshot_base.source_loaded_at,
        snapshot_base.record_loaded_at,
        snapshot_base.is_catalog_location,
        snapshot_base.has_location_dimension,
        snapshot_base.snapshot_date,
        snapshot_base.campaign_name,
        snapshot_base.max_air_temp_c,
        snapshot_base.min_air_temp_c,
        snapshot_base.avg_air_temp_c,
        snapshot_base.dew_point_temp_c,
        snapshot_base.wet_bulb_temp_c,
        snapshot_base.soil_surface_temp_c,
        snapshot_base.precipitation_mm,
        snapshot_base.relative_humidity_pct,
        snapshot_base.specific_humidity_kg_kg,
        snapshot_base.solar_radiation_allsky_mj_m2_day,
        snapshot_base.solar_radiation_clearsky_mj_m2_day,
        snapshot_base.wind_speed_mps,
        snapshot_base.wind_speed_max_mps,
        snapshot_base.wind_direction_deg,
        snapshot_base.surface_pressure_kpa,
        snapshot_base.cloud_cover_pct,
        snapshot_base.temp_range_c,
        snapshot_base.clear_sky_radiation_gap_mj_m2_day,
        snapshot_base.heat_index_c,
        snapshot_base.wind_chill_c,
        snapshot_base.vpd_kpa,
        snapshot_base.gdd_base_10_c_days,
        snapshot_base.weather_variable_non_null_count,
        snapshot_base.critical_null_count,
        snapshot_base.has_high_missing_data,
        snapshot_base.temperature_inconsistent,
        snapshot_base.temperature_outlier,
        snapshot_base.precipitation_outlier,
        snapshot_base.wind_outlier,
        snapshot_base.radiation_inconsistent,
        snapshot_base.frost_day,
        snapshot_base.heat_stress_day,
        snapshot_base.heavy_rain_day,
        snapshot_base.dry_day,
        snapshot_base.fungal_risk_day,
        snapshot_base.is_partial_latest_day,
        snapshot_base.is_quality_approved,
        snapshot_base.selection_strategy,
        snapshot_base._sdc_received_at,
        snapshot_base._sdc_extracted_at,
        snapshot_base._sdc_sequence,
        LEAST(
            ROUND(COALESCE(snapshot_base.precipitation_mm, 0.0) / 25.0 * 100.0, 2),
            100.0
        ) AS climate_rain_signal,
        ROUND(
            LEAST(
                100.0,
                (
                    COALESCE(LEAST(GREATEST(snapshot_base.vpd_kpa, 0.0), 4.0) / 4.0 * 60.0, 0.0)
                    + COALESCE(
                        (
                            100.0 - LEAST(GREATEST(snapshot_base.relative_humidity_pct, 0.0), 100.0)
                        ) * 0.25,
                        0.0
                    )
                    + CASE WHEN snapshot_base.dry_day THEN 15.0 ELSE 0.0 END
                )
            ),
            2
        ) AS climate_water_stress_signal,
        ROUND(
            LEAST(
                100.0,
                (
                    CASE WHEN snapshot_base.heat_stress_day THEN 50.0 ELSE 0.0 END
                    + CASE WHEN snapshot_base.frost_day THEN 50.0 ELSE 0.0 END
                    + COALESCE(
                        LEAST(GREATEST(snapshot_base.temp_range_c, 0.0), 20.0) / 20.0 * 25.0,
                        0.0
                    )
                    + CASE WHEN snapshot_base.max_air_temp_c >= 30.0 THEN 15.0 ELSE 0.0 END
                    + CASE WHEN snapshot_base.min_air_temp_c <= 2.0 THEN 10.0 ELSE 0.0 END
                )
            ),
            2
        ) AS climate_temperature_signal
    FROM snapshot_base
)

SELECT
    scored_snapshot.location_id,
    scored_snapshot.location_name,
    scored_snapshot.province_name,
    scored_snapshot.province_key,
    scored_snapshot.latitude,
    scored_snapshot.longitude,
    scored_snapshot.country_code,
    scored_snapshot.is_active,
    scored_snapshot.department_name,
    scored_snapshot.department_key,
    scored_snapshot.municipality_name,
    scored_snapshot.elevation_m,
    scored_snapshot.source_catalog,
    scored_snapshot.source_type,
    scored_snapshot.source_name,
    scored_snapshot.source_loaded_at,
    scored_snapshot.record_loaded_at,
    scored_snapshot.snapshot_date,
    scored_snapshot.campaign_name,
    scored_snapshot.is_catalog_location,
    scored_snapshot.has_location_dimension,
    scored_snapshot.weather_variable_non_null_count,
    scored_snapshot.critical_null_count,
    scored_snapshot.has_high_missing_data,
    scored_snapshot.is_quality_approved,
    scored_snapshot.is_partial_latest_day,
    scored_snapshot.selection_strategy,
    scored_snapshot.max_air_temp_c,
    scored_snapshot.min_air_temp_c,
    scored_snapshot.avg_air_temp_c,
    scored_snapshot.dew_point_temp_c,
    scored_snapshot.wet_bulb_temp_c,
    scored_snapshot.soil_surface_temp_c,
    scored_snapshot.precipitation_mm,
    scored_snapshot.relative_humidity_pct,
    scored_snapshot.specific_humidity_kg_kg,
    scored_snapshot.solar_radiation_allsky_mj_m2_day,
    scored_snapshot.solar_radiation_clearsky_mj_m2_day,
    scored_snapshot.wind_speed_mps,
    scored_snapshot.wind_speed_max_mps,
    scored_snapshot.wind_direction_deg,
    scored_snapshot.surface_pressure_kpa,
    scored_snapshot.cloud_cover_pct,
    scored_snapshot.temp_range_c,
    scored_snapshot.clear_sky_radiation_gap_mj_m2_day,
    scored_snapshot.heat_index_c,
    scored_snapshot.wind_chill_c,
    scored_snapshot.vpd_kpa,
    scored_snapshot.gdd_base_10_c_days,
    scored_snapshot.temperature_inconsistent,
    scored_snapshot.temperature_outlier,
    scored_snapshot.precipitation_outlier,
    scored_snapshot.wind_outlier,
    scored_snapshot.radiation_inconsistent,
    scored_snapshot.frost_day,
    scored_snapshot.heat_stress_day,
    scored_snapshot.heavy_rain_day,
    scored_snapshot.dry_day,
    scored_snapshot.fungal_risk_day,
    scored_snapshot.climate_rain_signal,
    scored_snapshot.climate_water_stress_signal,
    scored_snapshot.climate_temperature_signal,
    scored_snapshot._sdc_received_at,
    scored_snapshot._sdc_extracted_at,
    scored_snapshot._sdc_sequence,
    ROUND(
        (
            scored_snapshot.climate_rain_signal
            + scored_snapshot.climate_water_stress_signal
            + scored_snapshot.climate_temperature_signal
        ) / 300.0,
        4
    ) AS climate_index_total
FROM scored_snapshot
