{{ config(
    tags=['agro', 'mart', 'weather'],
    partition_by={'field': 'date', 'data_type': 'date', 'granularity': 'month'},
    cluster_by=['province_key', 'location_id']
) }}

WITH weather_quality AS (
    SELECT *
    FROM {{ ref('int_weather__daily_quality') }}
)

SELECT
    weather_quality.location_id,
    weather_quality.latitude,
    weather_quality.longitude,
    weather_quality.country_code,
    weather_quality.is_active_location,
    weather_quality.date,
    weather_quality.calendar_year,
    weather_quality.calendar_month,
    weather_quality.calendar_quarter,
    weather_quality.week_start,
    weather_quality.month_start,
    weather_quality.campaign_start_year,
    weather_quality.campaign_name,
    weather_quality.max_air_temp_c,
    weather_quality.min_air_temp_c,
    weather_quality.avg_air_temp_c,
    weather_quality.dew_point_temp_c,
    weather_quality.wet_bulb_temp_c,
    weather_quality.soil_surface_temp_c,
    weather_quality.precipitation_mm,
    weather_quality.relative_humidity_pct,
    weather_quality.specific_humidity_kg_kg,
    weather_quality.solar_radiation_allsky_mj_m2_day,
    weather_quality.solar_radiation_clearsky_mj_m2_day,
    weather_quality.wind_speed_mps,
    weather_quality.wind_speed_max_mps,
    weather_quality.wind_direction_deg,
    weather_quality.surface_pressure_kpa,
    weather_quality.cloud_cover_pct,
    weather_quality.temp_range_c,
    weather_quality.clear_sky_radiation_gap_mj_m2_day,
    weather_quality.heat_index_c,
    weather_quality.wind_chill_c,
    weather_quality.vpd_kpa,
    weather_quality.gdd_base_10_c_days,
    weather_quality.weather_variable_non_null_count,
    weather_quality.critical_null_count,
    weather_quality.has_high_missing_data,
    weather_quality.temperature_inconsistent,
    weather_quality.temperature_outlier,
    weather_quality.precipitation_outlier,
    weather_quality.wind_outlier,
    weather_quality.radiation_inconsistent,
    weather_quality.frost_day,
    weather_quality.heat_stress_day,
    weather_quality.heavy_rain_day,
    weather_quality.dry_day,
    weather_quality.fungal_risk_day,
    weather_quality.is_partial_latest_day,
    weather_quality.is_quality_approved,
    weather_quality.has_location_dimension,
    weather_quality.source_name,
    weather_quality.source_type,
    weather_quality.source_loaded_at,
    weather_quality.record_loaded_at,
    weather_quality._sdc_extracted_at,
    weather_quality._sdc_received_at,
    weather_quality._sdc_batched_at,
    weather_quality._sdc_deleted_at,
    weather_quality._sdc_sequence,
    weather_quality._sdc_table_version,
    COALESCE(location_dim.location_name, weather_quality.location_name) AS location_name,
    COALESCE(location_dim.province_name, weather_quality.province_name) AS province_name,
    COALESCE(location_dim.province_key, weather_quality.province_key) AS province_key
FROM weather_quality
LEFT JOIN {{ ref('dim_location') }} AS location_dim
    ON weather_quality.location_id = location_dim.location_id
